/* This is a basic example of a GUI interface generated by Java */

import javax.swing.JOptionPane;

public class HelloGui {
    public static void main (String[] args) {
        JOptionPane.showMessageDialog(null, "Hello, world");

    }
}
